<script>
import { ref, computed, onMounted, onUpdated, onUnmounted } from 'vue';
import { useRoute } from 'vue-router';

const datas = () => [
  /*
  {
    depth1: '',
    datas: [
      {
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/',
        status: 'ing', // ing, partend, end, moding, confirm
        create: '2023.03.24',
        log: [
          {
            // { date: '2023.03.24', text: '' },
          }
        ],
      },
    ],
  },
  */
  {
    depth1: '공통',
    datas: [
      {
        depth2: '로딩',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/loading-001',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '레이아웃',
        depth3: 'Type 1',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/layout-001',
        status: 'end',
        create: '2023.03.24',
        log: [],
      },
      {
        depth2: '레이아웃',
        depth3: 'Type 2',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/layout-002',
        status: 'end',
        create: '2023.03.24',
        log: [],
      },
      {
        depth2: '레이아웃',
        depth3: 'Type 3',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/layout-003',
        status: 'end',
        create: '2023.03.24',
        log: [],
      },
      {
        depth2: '얼럿',
        depth3: '버튼 한개',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/alert-001',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '얼럿',
        depth3: '버튼 두개',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/alert-002',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '얼럿',
        depth3: '타이틀만 있는 경우',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/alert-003',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '얼럿',
        depth3: '텍스트만 있는 경우',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/alert-004',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '토스트 얼럿',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/toast-alert-001',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '본인인증\nCommon_M00_p003',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/identification-001',
        status: 'end',
        create: '2023.03.24',
        log: [],
      },
      {
        depth2: '본인인증\nCommon_M00_p003',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/identification-002',
        status: 'end',
        create: '2023.03.24',
        log: [
          {
            date: '2023.05.05',
            text: '팝업 추가\n- 메뉴진입 본인인증 안내',
          },
        ],
      },
      {
        depth2: '신분증 촬영 및 정보 입력',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/id-shoot-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '신분증 촬영 및 정보 입력',
        depth3: '운전면허증',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/id-shoot-002',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '대출계산기',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/loan-calculator-001',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '직장검색',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/search-workplace-001',
        status: 'end',
        create: '2023.04.19',
        log: [],
      },
      {
        depth2: '날짜입력',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/enter-date-001',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '주소검색',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/search-address-001',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '약관동의',
        depth3: '상세',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/clause-detail-001',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '안내팝업',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/guide-001',
        status: 'end',
        create: '2023.03.31',
        log: [{ date: '2023.04.07', text: '앱 설치 안내 팝업 추가' }],
      },
      {
        depth2: '오류안내',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/error-001',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '앱 중계 페이지',
        depth3: '1Q 캐피탈\nCommon_M00_p007',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/redirect/app',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '앱 중계 페이지',
        depth3: '앱프리\nCommon_M00_p008',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/redirect/app-free',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '검색',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/search-001',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '서류등록',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/regist-document-001',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
    ],
  },
  {
    depth1: '메인',
    datas: [
      {
        depth2: 'WEB',
        depth3: '홈\nMain_M01_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/home-001',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'WEB',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/main-001',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '홈\nMain_M02_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/home-002',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/main-002',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '알림함\nMain_M06_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/push',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '렌탈 서비스\nMain_M07_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/rental',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '중고차 렌터카\nMain_M07_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/used-rental',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '오늘의 운세\nMain_M07_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/fortune',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '내대출\nMain_M03_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/my-loan',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '상품\nMain_M04_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/product',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: 'APP',
        depth3: '혜택\nMain_M05_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/main/benefit',
        status: '',
        create: '',
        log: [],
      },
    ],
  },
  {
    depth1: '전체메뉴',
    datas: [
      {
        depth2: '',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/menu',
        status: 'end',
        create: '2023.04.19',
        log: [],
      },
    ],
  },
  {
    depth1: '회원관리',
    datas: [
      {
        depth2: '로그인(WEB)\nMember_M01_p001\nMember_M02_p001',
        depth3: '아이디\n공동인증서',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sign/signin',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '로그인(WEB)\nMember_M01_p001\nMember_M02_p001',
        depth3: '아이디',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/sign-in-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 비밀번호 3개월 경과 안내\n- 통합 ID 선택',
          },
        ],
      },
      {
        depth2: '로그인(WEB)\nMember_M01_p001\nMember_M02_p001',
        depth3: '공동인증서',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/sign-in-certificate-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '아이디 찾기(WEB)',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sign-find-id-001',
        status: 'end',
        create: '2023.03.31',
        log: [{ date: '2023.04.07', text: '팝업 추가\n- 아이디 확인' }],
      },
      {
        depth2: '비밀번호 찾기(WEB)',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sign-reset-password-001',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '회원가입(WEB)',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sign-up-001',
        status: 'end',
        create: '2023.03.31',
        log: [{ date: '2023.04.07', text: '팝업 추가\n- 약관동의' }],
      },
      {
        depth2: '회원가입(APP)\nMember_M06_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sign/signup-app',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '회원가입(APP)\nMember_M06_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sign-up-app-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '간편비밀번호 불러오기(APP)\nMember_M07_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sign/load-pin',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '간편비밀번호 불러오기(APP)\nMember_M07_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sign-load-pin-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 비밀번호 입력\n- 가입 완료',
          },
        ],
      },
      {
        depth2: '로그인(APP)',
        depth3: '간편비밀번호',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/sign-in-pin-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 간편비밀번호 로그인',
          },
        ],
      },
      {
        depth2: '로그인(APP)',
        depth3: '간편비밀번호 초기화',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/sign-reset-pin-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 간편비밀번호 초기화\n- 새 비밀번호 입력\n- 새 비밀번호 재입력',
          },
        ],
      },
      {
        depth2: '로그인(APP)',
        depth3: '생체 인식',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/sign-in-biometrics-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
    ],
  },
  {
    depth1: '개인금융',
    datas: [
      {
        depth2: '공통',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-001',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: 'e하나신용대출\nPF_M01_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/e-hana',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: 'e하나신용대출\nPF_M01_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-e-hana-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- e하나신용대출(연계) 안내',
          },
        ],
      },
      {
        depth2: '행복아파트론\nPF_M02_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/happiness-apartment',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '행복아파트론\nPF_M02_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-happiness-apartment-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 아파트 등기부등본\n- 아파트 등기부등본 확인',
          },
          {
            date: '2023.04.14',
            text: '팝업 추가\n- 아파트 검색',
          },
        ],
      },
      {
        depth2: '아파트론\nPF_M03_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/apartment',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '원큐자동차담보대출\nPF_M04_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/one-q-auto',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '원큐자동차담보대출\nPF_M04_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-one-q-auto-001',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: '우수고객추가대출\nPF_M05_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/best-customer',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '우수고객추가대출\nPF_M05_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-best-customer-001',
        status: 'end',
        create: '2023.03.31',
        log: [],
      },
      {
        depth2: 'e임대주택론(임대보증금 담보대출)\nPF_M06_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/e-rental-house',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '스탁론\nPF_M07_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/stock',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '스탁론\nPF_M07_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-stock-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 연장신청 약관동의\n- 연장신청 계약선택\n- 연장신청 상품 만기현황 확인\n- 중도상환신청 계약선택\n- 중도상환금액 조회\n- 중도상환 신청확인\n- 중도상환 조건 입력',
          },
        ],
      },
      {
        depth2: '의료기할부\nPF_M08_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/medical-appliances',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '사업자주택담보대출\nPF_M09_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/business-house',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '사업자주택담보대출\nPF_M09_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-business-house-001',
        status: 'end',
        create: '2023.03.31',
        log: [
          {
            date: '2023.05.12',
            text: '팝업 추가\n- 주택정보 입력',
          },
        ],
      },
      {
        depth2: '내구소비재할부\nPF_M10_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/personal-loan/consumer-durables',
        status: 'pending',
        create: '',
        log: [],
      },
      {
        depth2: '통합 한도조회',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/personal-loan-etc-001',
        status: 'partend',
        create: '2023.03.31',
        log: [
          {
            date: '2023.04.07',
            text: '팝업 추가\n- 한도/금리 확인\n- 아파트 검색',
          },
        ],
      },
    ],
  },
  {
    depth1: '고객센터',
    datas: [
      {
        depth2: 'FAQ\nCustomer_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/faq',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '고객상담',
        depth3: '안내\nCustomer_M02_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/counseling-info',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '고객상담',
        depth3: '상담내용 작성\nCustomer_M02_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/counseling-regist',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '고객상담',
        depth3: '완료\nCustomer_M02_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/counseling-regist-complete',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '공지사항',
        depth3: '리스트\nCustomer_M03_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/notice-list',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '공지사항',
        depth3: '상세\nCustomer_M03_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/notice-detail',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '지점안내\nCustomer_M05_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/branch-list',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '고객센터 ARS안내\nCustomer_M07_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/ars',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '전화상담신청\nETC_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/reservation-counseling',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '전화상담신청\nETC_M01_p001',
        depth3: '완료\nETC_M01_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/reservation-counseling-complete',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '정책및약관\nCustomer_M08_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/clause',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '정책및약관\nCustomer_M08_p001',
        depth3: '상세\nCustomer_M08_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/clause-detail',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호헌장\nCustomer_M09_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-charter',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호조직\nCustomer_M09_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-organization',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호체계\nCustomer_M09_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-system',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호웹진\nCustomer_M09_p005',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-webzine',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호공시\nCustomer_M09_p006',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-notice-list',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호공시\nCustomer_M09_p006',
        depth4: '상세\nCustomer_M09_p007',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-notice-view',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금리인하요구권안내\nCustomer_M09_p008',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-interest-rate-cut-request-info',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '청약 철회권 안내\nCustomer_M09_p009',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-withdraw-subscription-info',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '중도상환수수료 면제\nCustomer_M09_p010',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-exemption-early-redemption-fee',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호자료\nCustomer_M09_p011',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-data',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '금융소비자보호\nCustomer_M09_p001',
        depth3: '금융소비자보호자료\nCustomer_M09_p011',
        depth4: '상세\nCustomer_M09_p012',
        depth5: '',
        depth6: '',
        path: '/customer/financial-consumer-protection-data-detail',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
    ],
  },
  {
    depth1: '재고금융 (영업용)',
    datas: [
      {
        depth2: '홈\nIF_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/home',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '한도조회\nIF_M08_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/loan-limit-inquiry',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '한도조회\nIF_M08_p001',
        depth3: '차량선택',
        depth4: '차량번호조회\nIF_M08_p002',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/loan-limit-inquiry-search-car-number',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '한도조회\nIF_M08_p001',
        depth3: '차량선택',
        depth4: '모델연식조회\nIF_M08_p003',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/loan-limit-inquiry-search-car-model',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '한도조회\nIF_M08_p001',
        depth3: '결과\nIF_M08_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/loan-limit-inquiry-complete',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '목록\nIF_M03_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/early-list',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '조건입력\nIF_M03_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/early-form',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '시뮬레이션\nIF_M03_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/early-simulation',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '즉시출금/가상계좌 입력 내용 확인\nIF_M03_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/early-confirm',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '신청완료\nIF_M03_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/early-complete',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '신청실패\nIF_M03_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/early-fail',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '중도상환',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/inventory-finance-early-001',
        status: 'end',
        create: '2023.04.14',
        log: [
          {
            date: '2023.04.21',
            text: '팝업 추가\n- 중도상환 입금 예약 신청_가상계좌 입금',
          },
        ],
      },
      {
        depth2: '만기연장',
        depth3: '목록\nIF_M04_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/extension-list',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '만기연장',
        depth3: '내역확인\nIF_M04_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/extension-view',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '만기연장',
        depth3: '조건입력\nIF_M04_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/extension-form',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '만기연장',
        depth3: '입력 내용 확인\nIF_M04_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/extension-confirm',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '만기연장',
        depth3: '약정완료\nIF_M04_p005',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/extension-complete',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '만기연장',
        depth3: '약정실패\nIF_M04_p005',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/extension-fail',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '추가서류등록\nIF_M05_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/add-documents',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '종료채권\nIF_M06_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/termination-bonds',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '신청현황',
        depth3: '목록\nIF_M02_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/state-list',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '신청현황',
        depth3: '정보입력\nIF_M02_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/state-add-info',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '신청현황',
        depth3: '차량사진 등록\nIF_M02_p007',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/state-add-car-photo',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '대출약정\nIF_M02_p007',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/loan-agreement',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '대출약정\nIF_M02_p007',
        depth3: '완료\nIF_M02_p008',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance/loan-agreement-complete',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '대출약정\nIF_M02_p007',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/inventory-finance-loan-agreement-001',
        status: 'end',
        create: '2023.05.05',
        log: [
          {
            date: '2023.05.16',
            text: '팝업 추가\n- 대출신청 확인',
          },
        ],
      },
      {
        depth2: '진행상태조회(URL)',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/inventory-finance-url-state-001',
        status: 'partend',
        create: '2023.05.05',
        log: [],
      },
    ],
  },
  {
    depth1: 'LM 블로그 (영업용)',
    datas: [
      {
        depth2: '대출상담\nLM_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/loan-counseling',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '대출상담\nLM_M01_p001',
        depth3: '계약정보\nLM_M01_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/loan-counseling-form',
        status: 'end',
        create: '2023.04.19',
        log: [],
      },
      {
        depth2: '대출상담\nLM_M01_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/lm-blog-loan-counseling-001',
        status: 'end',
        create: '2023.04.07',
        log: [
          {
            date: '2023.04.14',
            text: '팝업 추가\n- 아파트 검색\n- 사업자선택\n- 한도/금리 확인',
          },
        ],
      },
      {
        depth2: '빠른상담신청 내역\nLM_M02_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/quick-counseling',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: 'SMS 상담요청 내역\nLM_M03_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/sms-counseling',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: 'SMS 상담요청 내역\nLM_M03_p001',
        depth3: '상세\nLM_M03_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/sms-counseling-detail',
        status: 'end',
        create: '2023.04.19',
        log: [],
      },
      {
        depth2: '접속통계\nLM_M04_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/access-statistics',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '현황조회\nLM_M05_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog/status-inquiry',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
    ],
  },
  {
    depth1: 'LM 블로그 - 개인 (영업용)',
    datas: [
      {
        depth2: '홈\nLM_M06_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog-personal/home',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '전체메뉴\nLM_M06_p002',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog-personal/menu',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '빠른 대출 상담\nLM_M06_p004',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog-personal/quick-counseling',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: 'SMS 상담\nLM_M06_p005',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog-personal/sms-counseling',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '찾아오시는 길\nLM_M06_p006',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lm-blog-personal/map',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
    ],
  },
  {
    depth1: '중고차 (영업용)',
    datas: [
      {
        depth2: '팝업',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sales-used-car-001',
        status: 'end',
        create: '2023.05.05',
        log: [
          {
            date: '2023.05.10',
            text: '팝업 추가\n- 매매상사 약정 현황 조회\n- 차량정보 팝업\n- 수수료차감 팝업\n- 매매상사(차량 소유자)계좌 조회\n- 매매상사(차량 소유자)계좌 등록',
          },
        ],
      },
      {
        depth2: '홈\nUC_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/home',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '신규상담\nUC_M02_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/new-counseling',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '완료\nUC_M03_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-complete',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '자동승인\nUC_M03_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-auto-complete',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '실패\nUC_M03_p002',
        depth4: '기본',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-fail-001',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '실패\nUC_M03_p002',
        depth4: '고객정보 확인 불가',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-fail-002',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '실패\nUC_M03_p002',
        depth4: '대출신청금액이 큰 경우',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-fail-003',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '실패\nUC_M03_p002',
        depth4: '사업자정보가 없는 경우',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-fail-004',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '실패\nUC_M03_p002',
        depth4: '파일 업로드 실패',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-fail-005',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '불가능\nUC_M03_p005',
        depth4: '기본',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-impossible-001',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담등록\nUC_M03_p001',
        depth3: '불가능\nUC_M03_p005',
        depth4: '일반심사\n일반심사A\n정밀심사\n예외심사',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-impossible-002',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '상담변경\nUC_M04_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/counseling-edit',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '매매상사 온라인약정',
        depth3: '본인확인\nUC_M08_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/affiliate',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '매매상사 온라인약정',
        depth3: '정보 확인\nUC_M08_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/affiliate-confirm',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '매매상사 온라인약정',
        depth3: '계좌 정보 선택\nUC_M08_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/affiliate-form',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '매매상사 온라인약정',
        depth3: '완료\nUC_M08_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-used-car/affiliate-complete',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
    ],
  },
  {
    depth1: '신차 (영업용)',
    datas: [
      {
        depth2: '팝업',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/sales-new-car-001',
        status: 'end',
        create: '2023.05.05',
        log: [
          {
            date: '2023.05.12',
            text: '팝업 추가\n- 차량번호 등록\n- 판매점 조회\n- 판매사원 조회',
          },
        ],
      },
      {
        depth2: '홈\nNC_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/home',
        status: 'end',
        create: '2023.05.10',
        log: [],
      },
      {
        depth2: '신규상담\nNC_M02_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/new-counseling',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '상담등록\nNC_M03_p002',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/counseling',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '상담등록\nNC_M03_p002',
        depth3: '완료\nNC_M03_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/counseling-complete',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '상담등록\nNC_M03_p002',
        depth3: '대출불가\nNC_M03_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/counseling-fail',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '계약등록\nNC_M04_p002',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/add-contract',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '계약등록\nNC_M04_p002',
        depth3: '완료\nNC_M04_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/add-contract-complete',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '차량/저당 미등록 채권 안내\nNC_M08_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/sales-new-car/unregistered-bonds',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
    ],
  },
  {
    depth1: '재고금융실사 (영업용)',
    datas: [
      {
        depth2: 'IF_M11_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/inventory-finance-check/home',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '팝업',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/inventory-finance-check-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
    ],
  },
  {
    depth1: '리스/렌트 견적시스템 (영업용)',
    datas: [
      {
        depth2: '선구매\nLR_M02_p005',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lease-rent-estimation-system/pre-purchase',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '선구매\nLR_M02_p005',
        depth3: '등록 차량 상세\nLR_M02_p007',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/lease-rent-estimation-system/pre-purchase-car-detail',
        status: '',
        create: '',
        log: [],
      },
    ],
  },
  {
    depth1: '설비리스 (영업용)',
    datas: [
      {
        depth2: '팝업',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/equipment-lease-001',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '견적계산기\nEL_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/equipment-lease/estimate',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '견적계산기\nEL_M01_p001',
        depth3: '견적서 확인\nEL_M01_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/equipment-lease/estimate-result',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '현황조회',
        depth3: '견적\nEL_M02_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/equipment-lease/state-estimate',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '현황조회',
        depth3: '품의\nEL_M02_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/equipment-lease/state-internal-memo',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
    ],
  },
  {
    depth1: '설정',
    datas: [
      {
        depth2: '홈\nSetting_M00_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/setting/home',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: 'PUSH 알림 설정\nSetting_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/setting/push',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '공동인증서 가져오기\nSetting_M02_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/setting/certificate-import',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '공동인증서 내보내기\nSetting_M02_p003',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/setting/certificate-export',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '간편비밀번호 (재)등록',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/setting-reset-pin-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '얼굴인증 (재)등록',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/setting-reset-face-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '지문인증 (재)등록',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/setting-reset-fingerprint-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: 'Face ID (재)등록',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/setting-reset-face-id-001',
        status: 'end',
        create: '2023.04.07',
        log: [],
      },
      {
        depth2: '하나 원사인 이용안내\nSetting_M07_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/setting/hana-one-sign-guide',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
    ],
  },
  {
    depth1: '오토금융',
    datas: [
      {
        depth2: '견적',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-estimate-001',
        status: 'end',
        create: '2023.05.12',
        log: [
          {
            date: '2023.05.16',
            text: '팝업 추가\n- 진행이력 팝업\n- 이탈 안내팝업\n- 리스/렌트 비교 정보 팝업\n- 이용자 유형 선택 팝업\n- 제조사 선택\n- 종류 선택',
          },
        ],
      },
      {
        depth2: '장기렌터카\nAF_M01_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/long-rental',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '장기렌터카\nAF_M01_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-long-rental-001',
        status: 'end',
        create: '2023.04.14',
        log: [
          {
            date: '2023.04.21',
            text: '팝업 추가\n- 인도요청 정보입력',
          },
        ],
      },
      {
        depth2: '오토리스\nAF_M02_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/lease',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '오토리스\nAF_M02_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-lease-001',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '오토할부\nAF_M03_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/instalment',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '오토론\nAF_M04_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/loan',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '원큐다이렉트 오토론\nAF_M05_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/one-q-loan',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '원큐다이렉트 오토론\nAF_M05_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-one-q-loan-001',
        status: 'end',
        create: '2023.04.19',
        log: [],
      },
      {
        depth2: '중고차오토론\nAF_M06_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/used-loan',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '중고차오토론\nAF_M06_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-used-loan-001',
        status: 'end',
        create: '2023.04.19',
        log: [],
      },
      {
        depth2: '오토승계\nAF_M07_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/succession',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '오토승계\nAF_M07_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-succession-001',
        status: 'end',
        create: '2023.04.19',
        log: [
          {
            date: '2023.04.21',
            text: '팝업 추가\n- 본인인증\n- 양수인 신청\n- 리스 승계 상세정보\n- 리스상세조건\n- 렌트 승계 상세정보\n- 렌트상세조건\n- 양수인 정보입력\n- 신용정보조회동의\n- 위임동의 요청 완료\n- 양수인/신청인 본인확인\n- 양수인/신청인 본인확인\n- 위임동의 완료\n- 심사서류 등록\n- 위임장 동의\n- 양수인 신청완료',
          },
        ],
      },
      {
        depth2: '핫딜\nAF_M43_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/hot-deal',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '차바구니\nAF_M44_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/car-cart',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '차바구니\nAF_M44_p001',
        depth3: '등록없음',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/auto/car-cart-empty',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '차바구니\nAF_M44_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/auto-car-cart-001',
        status: 'end',
        create: '2023.05.05',
        log: [
          {
            date: '2023.05.16',
            text: '팝업 추가\n- 제조사 선택\n- 차종 선택',
          },
        ],
      },
    ],
  },
  {
    depth1: '기업금융',
    datas: [
      {
        depth2: '의료기리스\nBF_M01_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/business/medical-lease',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '산업재리스\nBF_M02_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/business/industrial-lease',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '설비리스\nBF_M05_p001',
        depth3: '상품안내',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/business/equipment-lease',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '설비리스\nBF_M05_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/business-equipment-lease-001',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
    ],
  },
  {
    depth1: '내 대출',
    datas: [
      {
        depth2: '홈\nMy_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/home',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '홈\nMy_M01_p001',
        depth3: '계약미보유',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/empty',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '홈\nMy_M01_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-home-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '상세계약현황\nMy_M01_p002',
        depth3: '개인금융',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-personal',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '상세계약현황\nMy_M01_p002',
        depth3: '스탁론',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-stock',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '상세계약현황\nMy_M01_p002',
        depth3: '중도금대출',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-intermediate',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '상세계약현황\nMy_M01_p002',
        depth3: '오토금융',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-auto',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '상세계약현황\nMy_M01_p002',
        depth3: '일반할부',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-instalment',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '상세계약현황\nMy_M01_p002',
        depth3: '의료기할부',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-medical-instalment',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '결제/청구정보\nMy_M01_p004',
        depth3: '가상계좌',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-payment-virtual',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '결제/청구정보\nMy_M01_p004',
        depth3: '자동이체계좌',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/detail-payment-auto',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '정비이력\nMy_M01_p005',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/maintenance-history',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '범칙금\nMy_M01_p006',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/penalty',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '자동차세\nMy_M01_p007',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/car-tax',
        status: 'end',
        create: '2023.04.21',
        log: [],
      },
      {
        depth2: '지정운전자\nMy_M01_p008',
        depth3: '등록 전',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/designation-driver-empty',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '지정운전자\nMy_M01_p008',
        depth3: '등록 후',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/designation-driver',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '지정운전자\nMy_M01_p008',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-designation-driver-001',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/progress',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '본인인증\nMy_M03_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/progress-identification',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-progress-001',
        status: 'partend',
        create: '2023.04.14',
        log: [
          {
            date: '2023.04.21',
            text: '팝업 추가\n- 약관동의',
          },
          {
            date: '2023.04.28',
            text: '팝업 추가\n- 계약서류 조회\n- 이메일 전송\n- 신용정보조회동의\n- 신용정보조회동의 완료\n- 본인확인(URL진입)\n- 계약정보확인\n- 물품수령정보\n- 동의하기\n- 확인완료\n- 할부상담신청\n- 한도조회결과\n- 할부신청정보입력\n- 품목 검색\n- 할부상담 결과안내',
          },
          {
            date: '2023.05.05',
            text: '팝업 추가\n- 약정 정보 확인\n- 계약정보 최종확인\n- 주문서\n- 리스계약확인서\n- 약정완료\n- 약정실패',
          },
        ],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '팝업 001',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-progress-002',
        status: 'end',
        create: '2023.04.14',
        log: [
          {
            date: '2023.04.21',
            text: '팝업 추가\n- 약관동의\n- 추가설명 여부\n- 약관상세_중고차 대출사기 방지 안내문\n- 약관상세_대출상담사 설명 확인서\n- 계약신청 정보입력\n- 청구 정보입력\n- 결제 정보입력\n- 결제 정보입력\n- 추가 정보입력\n- 기약정 안내_진행\n- 기약정 안내_완료\n- 금융조건 정보입력\n- 1원계좌 인증\n- 계약정보 최종확인\n- 계약사항 확인\n- 자동송금\n- 약정완료 신용대출\n- 약정완료 중도금대출\n- 약정완료 일반할부금융\n- 약정완료 자동송금대상(영업시간 내)\n- 약정완료 자동송금대상(영업시간 외)\n- 약정실패 신용대출\n- 약정실패 중도금대출\n- 약정실패 일반할부금\n- 약정실패 Fraud대상자\n- 약정실패 오류\n- 금리인하요구권 안내\n- 청약철회권 안내\n- 상품설명서 확인 안내(공통)\n- 상품설명에 대한 확인(공통)\n- 승계 본인확인\n- 승계확약 확인\n- 승계확약서 확인\n- 승계 약정 중요사항 확인',
          },
          {
            date: '2023.05.05',
            text: '팝업 추가\n- 승계확약서_오토리스\n- 승계확약서_오토리스\n- 계약정보 최종확인_리스 승계 후\n- 계약정보 최종확인_장기렌터카 승계전\n- 계약정보 최종확인_장기렌터카 신규/승계후/연장',
          },
        ],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '팝업 002',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-progress-012',
        status: 'end',
        create: '2023.05.05',
        log: [
          {
            date: '2023.05.12',
            text: '팝업 추가\n- 중고차 오토론_약관동의\n- 계약정보 최종확인_중고차오토론\n- 계약정보 최종확인_약정정보확인\n- 약정완료_오토금융\n- 중도상환 수수료 산식 팝업\n- 약관상세_할부금 수령 위임안내\n- 계약정보 최종확인_중고차 할부\n- 계약정보 최종확인_약정정보확인 중고차할부',
          },
        ],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 001 (일반신용대출)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-003',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 002 (일반할부금융)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-004',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 003 (중도금대출)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-005',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 004 (자동차오토론)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-006',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 005 (중고차오토론)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-007',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 006 (자동차할부금융)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-008',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 007 (자동차금융리스)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-009',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 008 (자동차운용리스)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-010',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '진행상태조회\nMy_M03_p001',
        depth3: '온라인약정',
        depth4: '상품설명서 009 (일반리스)',
        depth5: '팝업',
        depth6: '',
        path: '/guide/my-loan-progress-011',
        status: 'end',
        create: '2023.04.26',
        log: [],
      },
      {
        depth2: '중도상환신청',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-intermediate-001',
        status: 'end',
        create: '2023.04.14',
        log: [],
      },
      {
        depth2: '증명서 조회/발급',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-certificate-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '근저당설정 조회/해지',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-mortgage-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-post-maturity-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '렌탈',
        depth4: '신청전\nMy_M08_p001',
        depth5: '',
        depth6: '',
        path: '/my-loan/post-maturity-rental-before',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '렌탈',
        depth4: '신청후\nMy_M08_p002',
        depth5: '',
        depth6: '',
        path: '/my-loan/post-maturity-rental-after',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '렌탈',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-post-maturity-rental-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '리스',
        depth4: '신청전\nMy_M08_p003',
        depth5: '',
        depth6: '',
        path: '/my-loan/post-maturity-lease-before',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '리스',
        depth4: '신청후\nMy_M08_p004',
        depth5: '',
        depth6: '',
        path: '/my-loan/post-maturity-lease-after',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '만기후처리',
        depth3: '리스',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-post-maturity-lease-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '금리인하요구권신청\nMy_M05_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/interest-rate-cut-request',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '금리인하요구권신청\nMy_M05_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-interest-rate-cut-request-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '청약철회권신청\nMy_M06_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/subscription-withdrawal-right',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '청약철회권신청\nMy_M06_p001',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-subscription-withdrawal-right-001',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '서류등록',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-loan-add-documents-001',
        status: 'partend',
        create: '2023.04.28',
        log: [],
      },
      {
        depth2: '서류등록',
        depth3: '등록완료\nMy_M07_p001',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-loan/add-documents-complete',
        status: 'end',
        create: '2023.04.28',
        log: [],
      },
    ],
  },
  {
    depth1: '내 정보',
    datas: [
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/home',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '내정보 변경\nMI_M01_p002',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/edit',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '내정보 변경\nMI_M01_p002',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-edit-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '자동이체 계좌 변경\nMI_M01_p003',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/direct-debit-account',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '자동이체 계좌 변경\nMI_M01_p003',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-direct-debit-account-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '청구정보 변경\nMI_M01_p004',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/billing',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '청구정보 변경\nMI_M01_p004',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-billing-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '비밀번호 변경',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-password-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '하나머니\nMI_M01_p005',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/hana-money',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '마케팅 수신 동의 변경\nMI_M01_P006',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/marketing',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '마케팅 수신 동의 변경\nMI_M01_P006',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-marketing-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '회원탈퇴\nMI_M01_p007',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/withdraw-member',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '내정보 관리\nMI_M01_p001',
        depth3: '회원탈퇴\nMI_M01_p007',
        depth4: '완료\nMI_M01_p008',
        depth5: '',
        depth6: '',
        path: '/my-info/withdraw-member-complete',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '하나머니',
        depth3: '하나머니 소개\nMI_M01_p009',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/join-hana-money',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '하나머니',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-join-hana-money-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '하나캐피탈 멤버십',
        depth3: '가입',
        depth4: '멤버십 안내\nMI_M01_p010',
        depth5: '',
        depth6: '',
        path: '/my-info/join-membership',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '하나캐피탈 멤버십',
        depth3: '가입',
        depth4: '완료\nMI_M01_p011',
        depth5: '',
        depth6: '',
        path: '/my-info/join-membership-complete',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '하나캐피탈 멤버십',
        depth3: '가입',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-join-membership-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '하나캐피탈 멤버십',
        depth3: '탈퇴',
        depth4: '완료\nMI_M01_p012',
        depth5: '',
        depth6: '',
        path: '/my-info/withdraw-membership-complete',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '하나캐피탈 멤버십',
        depth3: '탈퇴',
        depth4: '팝업',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-withdraw-membership-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '자동차 시세조회\nMI_M01_p013',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/market-price-car',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '자동차 시세조회\nMI_M01_p013',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-market-price-car-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
      {
        depth2: '부동산 시세조회\nMI_M01_p014',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/my-info/market-price-realty',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '부동산 시세조회\nMI_M01_p014',
        depth3: '팝업',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/guide/my-info-market-price-realty-001',
        status: 'end',
        create: '2023.05.05',
        log: [],
      },
    ],
  },
  {
    depth1: '회사소개',
    datas: [
      {
        depth2: '회사소개\nCompany_M08_p001',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/about',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: 'CEO 인사말\nCompany_M08_p002',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/ceo',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '연혁\nCompany_M08_p003',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/history',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '사업분야\nCompany_M08_p004',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/business-areas',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: 'IR정보\nCompany_M08_p005',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/ir-list',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: 'IR정보\nCompany_M08_p005',
        depth3: '상세\nCompany_M08_p006',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/ir-detail',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '지속가능경영\nCompany_M08_p007',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/sustainable-management-list',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '지속가능경영\nCompany_M08_p007',
        depth3: '상세\nCompany_M08_p008',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/sustainable-management-detail',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '하나금융그룹\nCompany_M08_p009',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/group',
        status: '',
        create: '',
        log: [],
      },
      {
        depth2: '윤리헌장\nCompany_M08_p010',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/ethics-charter',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '윤리강령\nCompany_M08_p011',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/ethics-code',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '인권선언문\nCompany_M08_p012',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/human-rights-declaration',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '인권선언문 구성체계\nCompany_M08_p013',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/human-rights-declaration-structure',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '채용안내\nCompany_M08_p014',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/recruit-guide',
        status: 'end',
        create: '2023.05.12',
        log: [],
      },
      {
        depth2: '인사/복리후생\nCompany_M08_p015',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/personnel-welfare',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '채용공고\nCompany_M08_p016',
        depth3: '',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/recruit-list',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
      {
        depth2: '채용공고\nCompany_M08_p016',
        depth3: '상세\nCompany_M08_p017',
        depth4: '',
        depth5: '',
        depth6: '',
        path: '/company/recruit-detail',
        status: 'end',
        create: '2023.05.16',
        log: [],
      },
    ],
  },
];

export default {
  setup() {
    const tableDatas = datas();

    const route = useRoute();

    const statusText = {
      pending: '보류',
      ing: '작업중',
      partend: '부분작업완료',
      end: '작업완료',
      moding: '수정중',
      confirm: '검수완료',
    };
    const dates = (() => {
      const array = [];

      const add = (date) => {
        if (
          typeof date === 'string' &&
          date.length &&
          array.indexOf(date) === -1
        ) {
          array.push(date);
        }
      };

      tableDatas.forEach((item) => {
        item.datas.forEach((data) => {
          add(data.create);

          data.log.sort((a, b) => {
            var dateA = a.date.toUpperCase();
            var dateB = b.date.toUpperCase();
            if (dateA < dateB) {
              return -1;
            }
            if (dateA > dateB) {
              return 1;
            }
            return 0;
          });

          data.log.forEach((log) => {
            add(log.date);
          });

          if (data.log.length) {
            data.update = data.log[data.log.length - 1].date;
          }
        });
      });

      array.sort();

      return array;
    })();
    const latestDate = dates[dates.length - 1];

    const renderVal = (datas, i, key, testKey) => {
      const val = datas[i][key];
      const testVal = testKey && datas[i][testKey];
      const prevIndex = i - 1;
      const result = val.replace(/\n/g, '<br>');

      if (!(prevIndex >= 0 && datas[prevIndex])) return result;

      const noRender = datas[prevIndex][key] === val;

      if (testVal) {
        if (testVal === datas[prevIndex][testKey] && noRender) {
          return '';
        } else {
          return result;
        }
      } else {
        if (noRender) {
          return '';
        } else {
          return result;
        }
      }
    };

    const printVal = (val) => {
      return val.replace(/\n/g, '<br>');
    };

    const bottomBar = ref(null);
    const fake = ref(null);

    const path = computed(() => {
      return route.path;
    });

    const update = () => {
      if (bottomBar.value && fake.value) {
        const height = bottomBar.value.offsetHeight;
        fake.value.style.height = `${height}px`;
      }
    };

    const scroll = () => {
      const html = document.getElementsByTagName('html')[0];

      if (html && bottomBar.value) {
        bottomBar.value.style.marginLeft = `-${html.scrollLeft}px`;
      }
    };

    const resize = () => {
      scroll();
      update();
    };

    const load = () => {
      resize();
    };

    onMounted(() => {
      update();

      window.addEventListener('load', load);
      window.addEventListener('scroll', scroll);
      window.addEventListener('resize', resize);
    });

    onUpdated(() => {
      update();
    });

    onUnmounted(() => {
      window.removeEventListener('load', load);
      window.removeEventListener('scroll', scroll);
      window.removeEventListener('resize', resize);
    });

    return {
      bottomBar,
      fake,
      tableDatas,
      statusText,
      latestDate,
      path,
      renderVal,
      printVal,
    };
  },
};
</script>

<template>
  <div class="contIndex">
    <div class="index-wrap">
      <div class="index">
        <h1 class="index-title">하나캐피탈 - 모바일</h1>
        <div class="index-gnb">
          <div class="index-links">
            <div class="index-links__inner">
              <a
                :href="`${
                  path.match('guide-index') ? '..' : '.'
                }/guide/component`"
                target="_blank"
                class="index-button"
              >
                컴포넌트 가이드
              </a>
            </div>
          </div>
        </div>
        <div class="index-bottom" ref="bottomBar">
          <div class="index-links">
            <div class="index-links__inner">
              <a
                v-for="(item, i) in tableDatas"
                :key="i"
                :href="`#section${i}`"
                class="index-button"
              >
                {{ item.depth1 }}
              </a>
            </div>
          </div>
        </div>
        <div class="index-datas" id="indexTable">
          <div
            class="index-section"
            v-for="(item, i) in tableDatas"
            :key="i"
            :id="`section${i}`"
          >
            <h2 class="index-section__title">{{ item.depth1 }}</h2>
            <div class="index-table">
              <table>
                <colgroup>
                  <col width="160px" />
                  <col width="160px" />
                  <col width="160px" />
                  <col width="160px" />
                  <col width="160px" />
                  <col />
                  <col width="100px" />
                  <col width="100px" />
                  <col width="110px" />
                  <col width="300px" />
                </colgroup>
                <thead>
                  <tr>
                    <th>depth2</th>
                    <th>depth3</th>
                    <th>depth4</th>
                    <th>depth5</th>
                    <th>depth6</th>
                    <th>path</th>
                    <th>status</th>
                    <th>create</th>
                    <th>update</th>
                    <th>log</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="(data, i) in item.datas" :key="i">
                    <td v-html="renderVal(item.datas, i, 'depth2')"></td>
                    <td
                      v-html="renderVal(item.datas, i, 'depth3', 'depth2')"
                    ></td>
                    <td
                      v-html="renderVal(item.datas, i, 'depth4', 'depth3')"
                    ></td>
                    <td
                      v-html="renderVal(item.datas, i, 'depth5', 'depth4')"
                    ></td>
                    <td
                      v-html="renderVal(item.datas, i, 'depth6', 'depth5')"
                    ></td>
                    <td>
                      <a
                        :href="`${path.match('guide-index') ? '..' : '.'}${
                          data.path
                        }`"
                        target="_blank"
                      >
                        {{ data.path }}
                      </a>
                    </td>
                    <td>
                      <span
                        v-if="data.status.length"
                        :class="`index-status index-status--${data.status}`"
                      >
                        {{ statusText[data.status] }}
                      </span>
                    </td>
                    <td
                      :class="{
                        'is-emphasis': latestDate === data.create,
                      }"
                    >
                      {{ data.create }}
                    </td>
                    <td
                      :class="[
                        {
                          'is-emphasis': latestDate === data.update,
                        },
                      ]"
                    >
                      {{ data.update }}
                    </td>
                    <td>
                      <ul v-if="data.log.length" class="index-log">
                        <li
                          v-for="(log, i) in data.log"
                          :key="i"
                          :class="[
                            'index-log__item',
                            {
                              'is-emphasis': latestDate === log.date,
                            },
                          ]"
                        >
                          <div class="index-log__date">
                            <span>[{{ log.date }}]</span>
                          </div>
                          <div
                            class="index-log__text"
                            v-html="printVal(log.text)"
                          ></div>
                        </li>
                      </ul>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="index-fake-botttom" ref="fake"></div>
  </div>
</template>

<style lang="scss">
@import '@/assets/scss/views/uiGuide/GuideIndex.scss';
</style>
